FROM {{ dist }}:{{ release }}
MAINTAINER {{ maintainer }}
RUN echo 'http_proxy="<%= @proxy %>"' >> /etc/environment
RUN echo 'https_proxy="<%= @proxy %>"' >> /etc/environment
ENV http_proxy=<%= @proxy %>
ENV https_proxy=<%= @proxy %>
RUN echo 'Acquire::Http::Proxy "<%= @proxy %>";' >> /etc/apt/apt.conf.d/90proxy
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y dpkg-dev aptitude build-essential ; mkdir -p /usr/lib/pbuilder/
COPY scripts/pbuilder-satisfydepends* /usr/lib/pbuilder/
